// Generated by CoffeeScript 1.7.1
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

(function(self) {
  var BlobPart, FormData, LF, Promise, StringPart, support;
  if (self.FormData) {
    return;
  }
  Promise = require('promise-polyfill');
  support = {
    arrayBuffer: __indexOf.call(self, 'ArrayBuff') >= 0,
    blob: __indexOf.call(self, 'FileReader') >= 0 && __indexOf.call(self, 'Blob') >= 0 && (function() {
      try {
        new Blob();
        return true;
      } catch (_error) {
        return false;
      }
    })()
  };
  LF = "\r\n";
  StringPart = (function() {
    function StringPart(name, value) {
      this.name = name;
      this.value = value;
    }

    StringPart.prototype.convertToString = function() {
      return new Promise(function(resolve) {
        var s;
        s = [];
        s.push("Content-Disposition: form-data; name=" + this.name + ";" + LF + LF);
        s.push("" + this.value + LF);
        return resolve(s.join(''));
      });
    };

    return StringPart;

  })();
  BlobPart = (function() {
    function BlobPart(name, filename, souce) {
      this.name = name;
      this.filename = filename;
      this.souce = souce;
    }

    BlobPart.prototype._readArrayBufferAsString = function(buff) {
      var view;
      view = new Uint8Array(buff);
      return view.reduce(function(acc, b) {
        acc.push(String.fromCharCode(b));
        return acc;
      }, new Array(view.length)).join('');
    };

    BlobPart.prototype._readBlobAsArrayBuffer = function() {
      self = this;
      return new Promise(function(resolve) {
        var reader;
        reader = new FileReader();
        reader.readAsArrayBuffer(self.souce);
        return reader.onload = function() {
          return resolve(self._readArrayBufferAsString(reader.result));
        };
      });
    };

    BlobPart.prototype._readBlobAsBinary = function() {
      return new Promise(function(resolve) {
        return resolve(this.souce.getAsBinary());
      });
    };

    BlobPart.prototype.convertToString = function() {
      var s;
      s = [];
      s.push("Content-Disposition: form-data; name=" + this.name + "; filename=" + this.filename + LF);
      s.push("Content-Type: " + this.souce.type + LF + LF);
      if (support.blob && support.arrayBuffer) {
        return this._readBlobAsArrayBuffer().then(function(strings) {
          s.push(strings + LF);
          return s.join('');
        });
      } else {
        return this._readBlobAsBinary().then(function(strings) {
          s.push(strings + LF);
          return s.join('');
        });
      }
    };

    return BlobPart;

  })();
  FormData = (function() {
    function FormData() {
      this.polyfill = true;
      this._parts = [];
      this.boundary = "--------FormData" + Math.random();
    }

    FormData.prototype.append = function(key, value) {
      var part;
      part = null;
      if (typeof value === "string") {
        part = new StringPart(key, value);
      } else if (value instanceof Blob) {
        part = new BlobPart(key, value.name, value);
      } else {
        part = new StringPart(key, value);
      }
      if (part) {
        this._parts.push(part);
      }
      return this;
    };

    FormData.prototype.toString = function() {
      var boundary, lines, parts;
      boundary = this.boundary;
      lines = [];
      parts = this._parts;
      return new Promise(function(resolve) {
        return parts.reduce(function(promise, part) {
          return promise.then(function(line) {
            return part.convertToString().then(function(strings) {
              lines.push("--" + boundary + LF);
              lines.push(strings);
              return lines;
            });
          });
        }, new Promise()).join('');
      }).then(function(lines) {
        lines.push("--" + boundary + "--");
        return lines.join('');
      });
    };

    return FormData;

  })();
  return self.FormData = FormData;
})(typeof self !== 'undefined' ? self : this);
